### ISSUE TITLE
[feature request] configuration support

### ISSUE THREAD

**Issue by GasparVardanyan** [jsspencer/pomo#10]
It'll be nice to have a config file to be abele to more extensibly configure pomo.
For example, in my [simple implementation](https://gitlab.com/GasparVardanyan/utilsbin/-/blob/master/spt) (but ofcourse this one is better) I have 4 short breaks, one long, and one without time limitation.
I'll like to be able to configute how many short breaks there would be before the long one (with custom labels and different notification sounds), to have nested pomodoros, time limitation free breaks (to prepare to start the work again)... and all of that in a config file, to have several profiles (configurations).

**Comment by GasparVardanyan** [comment]
And to be able to run custom scripts between blocks 🙂
... to send a notification to my phone after the break period is finished.

**Comment by GasparVardanyan** [comment]
P.S. sorry ))

**Comment by jsspencer** [comment]
Patches always welcome :)

As it happens, I already had local changes for adding a config file. Making the callback at the end of each period configurable was just a few lines. I think this should be sufficient for what you want to do. Note you can also source pomo.sh and use the functions as a building block for your own preferences.
